Importing python Libraries

In [ ]:
!pip install datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datasets import load_dataset



Text Preprocessing

In [ ]:
df = load_dataset("legacy-datasets/banking77")

# Access the 'train' split (or 'test' or 'validation' if needed)
train_df = df["train"].to_pandas()  # Convert to pandas DataFrame

# Now you can use head()
train_df.head()

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


text  label
0                     I am still waiting on my card?     11
1  What can I do if my card still hasn't arrived ...     11
2  I have been waiting over a week. Is the card s...     11
3  Can I track my card while it is in the process...     11
4  How do I know if I will get my card, or if it ...     11

In [ ]:
train_df.shape

(10003, 2)

In [ ]:

import re


# Load the dataset and select the 'train' split (or any other split you need)
df = load_dataset("legacy-datasets/banking77")["train"].to_pandas()

def remove_punctuation(text):
  return re.sub(r'[^\w\s]', '', text)

# Assuming 'df' is your DataFrame and 'text' is the column containing text data
df['text_without_punctuation'] = df['text'].apply(remove_punctuation)

# Display the updated DataFrame
df.head()

text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  
0                      I am still waiting on my card  
1  What can I do if my card still hasnt arrived a...  
2  I have been waiting over a week Is the card st...  
3  Can I track my card while it is in the process...  
4  How do I know if I will get my card or if it i...

In [ ]:
# Convert text to lowercase
df['text_lower'] = df['text_without_punctuation'].str.lower()

# Display the updated DataFrame
df.head()

text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  
0                      i am still waiting on my card  
1  what can i do if my card still hasnt arrived a...  
2  i have been waiting over a week is the card st...  
3  can i track my card while it is in the process...  
4  how do i know if i will get my card or if it i...

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

# Apply remove_stopwords to the lowercase text column
df['text_without_stopwords'] = df['text_lower'].apply(remove_stopwords)

# Display the updated DataFrame
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords  
0                still waiting card  
1  card still hasnt arrived 2 weeks  
2    waiting week card still coming  
3       track card process delivery  
4                know get card lost

In [ ]:
import nltk
from nltk.stem import PorterStemmer

# Download the 'punkt_tab' data package
nltk.download('punkt_tab')

def stem_text(text):
    stemmer = PorterStemmer()
    words = nltk.word_tokenize(text)  # Tokenize the text into words
    stemmed_words = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed_words)  # Join stemmed words back into a string

# Apply stemming to your preprocessed text column
df['text_stemmed'] = df['text_without_stopwords'].apply(stem_text)

# Display the updated DataFrame
df.head()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords                   text_stemmed  
0                still waiting card                still wait card  
1  card still hasnt arrived 2 weeks  card still hasnt arriv 2 week  
2    waiting week card still coming      wait week card still come  
3       track card process delivery    track card process deliveri  
4                know get card lost             know get card lost

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

# Download the 'averaged_perceptron_tagger' data package, specifically for English
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')


def lemmatize_text(text):
    lemmatizer = WordNetLemmatizer()

    # Function to get wordnet pos tag
    def get_wordnet_pos(word):
        """Map POS tag to first character lemmatize() accepts"""
        tag = nltk.pos_tag([word])[0][1][0].upper()
        tag_dict = {"J": wordnet.ADJ,
                    "N": wordnet.NOUN,
                    "V": wordnet.VERB,
                    "R": wordnet.ADV}

        return tag_dict.get(tag, wordnet.NOUN) # Default to noun if not found

    # Tokenize the text into words
    words = nltk.word_tokenize(text)

    # Lemmatize each word with its appropriate POS tag
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]

    return ' '.join(lemmatized_words)  # Join lemmatized words back into a string

# Apply lemmatization to your preprocessed text column
df['text_lemmatized'] = df['text_without_stopwords'].apply(lemmatize_text)

# Display the updated DataFrame
df.head()

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords                   text_stemmed  \
0                still waiting card                still wait card   
1  card still hasnt arrived 2 weeks  card still hasnt arriv 2 week   
2    waiting week card still coming      wait week card still come   
3       track card process delivery    track card process deliveri   
4                know get card lost             know get card lost   

                  text_lemmatized  
0                 still wait card  
1  card still hasnt arrive 2 week  
2       wait week card still come  
3     track card process delivery  
4              know get card lose

Feature Extrction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Assuming df['text'] contains preprocessed text
X = df['text']
# Create a TF-IDF vectorizer
vectorizer = TfidfVectorizer()
# Fit and transform the text data
X_tfidf = vectorizer.fit_transform(X)
# Print the TF-IDF matrix
print(X_tfidf.toarray())
# Print the vocabulary (feature names)
print(vectorizer.get_feature_names_out())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '10' ... 'youre' 'yours' 'zero']


In [ ]:
import gensim
from gensim.models import Word2Vec

# Tokenize the text data
tokenized_text = df['text_lemmatized'].apply(lambda x: x.split()).tolist()

# Train Word2Vec model
model = Word2Vec(sentences=tokenized_text, vector_size=100, window=5, min_count=1, workers=4)

# Function to create sentence embeddings by averaging word embeddings
def create_sentence_embedding(text):
    words = text.split()
    embeddings = [model.wv[word] for word in words if word in model.wv]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(100)

# Apply the function to your text data
df['word2vec_embedding'] = df['text_lemmatized'].apply(create_sentence_embedding)
df.head()

text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords                   text_stemmed  \
0                still waiting card                still wait card   
1  card still hasnt arrived 2 weeks  card still hasnt arriv 2 week   
2    waiting week card still coming      wait week card still come   
3       track card process delivery    track card process deliveri   
4                know get card lost             know get card lost   

                  text_lemmatized  \
0                 still wait card   
1  card still hasnt arrive 2 week   
2       wait week card still come   
3     track card process delivery   
4              know get card lose   

                                  word2vec_embedding  
0  [0.14740552, 0.49287963, -0.18150012, -0.17983...  
1  [0.13618965, 0.46497932, -0.19877052, -0.20180...  
2  [0.15524864, 0.5264305, -0.20263293, -0.218502...  
3  [0.12745024, 0.42099524, -0.14665046, -0.15708...  
4  [0.1624019, 0.5341237, -0.16616106, -0.2140869...

In [ ]:
import gensim.downloader as api

# Download and load GloVe embeddings
glove_model = api.load("glove-wiki-gigaword-100")

# Function to create sentence embeddings by averaging word embeddings
def create_sentence_embedding(text):
    words = text.split()
    embeddings = [glove_model[word] for word in words if word in glove_model]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(100)

# Apply the function to your text data
df['glove_embedding'] = df['text_lemmatized'].apply(create_sentence_embedding)
df.head()

[==================================================] 100.0% 128.1/128.1MB downloaded


text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords                   text_stemmed  \
0                still waiting card                still wait card   
1  card still hasnt arrived 2 weeks  card still hasnt arriv 2 week   
2    waiting week card still coming      wait week card still come   
3       track card process delivery    track card process deliveri   
4                know get card lost             know get card lost   

                  text_lemmatized  \
0                 still wait card   
1  card still hasnt arrive 2 week   
2       wait week card still come   
3     track card process delivery   
4              know get card lose   

                                  word2vec_embedding  \
0  [0.14740552, 0.49287963, -0.18150012, -0.17983...   
1  [0.13618965, 0.46497932, -0.19877052, -0.20180...   
2  [0.15524864, 0.5264305, -0.20263293, -0.218502...   
3  [0.12745024, 0.42099524, -0.14665046, -0.15708...   
4  [0.1624019, 0.5341237, -0.16616106, -0.2140869...   

                                     glove_embedding  
0  [-0.009803335, 0.21815668, 0.41252002, -0.5842...  
1  [-0.11511, 0.24187951, 0.3228995, -0.26670733,...  
2  [-0.052110992, 0.2585094, 0.47082195, -0.54346...  
3  [0.10424499, -0.010438494, 0.14174, -0.1618157...  
4  [0.21422, 0.262195, 0.611615, -0.63392997, -0....

In [ ]:
!pip install fasttext

import fasttext
import numpy as np

# Assuming 'text_lemmatized' column in your DataFrame contains preprocessed text
text_data = df['text_lemmatized'].str.cat(sep=' ')  # Concatenate all text into a single string

# Save the text data to a temporary file
with open('temp_text.txt', 'w') as f:
    f.write(text_data)

# Train FastText model using the temporary file
model_fasttext = fasttext.train_unsupervised('temp_text.txt', model='skipgram', dim=100)

# Function to create sentence embeddings by averaging word embeddings
def create_sentence_embedding(text):
    words = text.split()
    embeddings = [model_fasttext.get_word_vector(word) for word in words]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(100)

# Apply the function to your text data
df['fasttext_embedding'] = df['text_lemmatized'].apply(create_sentence_embedding)
df.head()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 5.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313473 sha256=f0b7ecaebb94b096b03d56da4771e701ad4d5becbdccb4e0adffcccc96eba4f6
  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3
Successfully built fasttext


text  label  \
0                     I am still waiting on my card?     11   
1  What can I do if my card still hasn't arrived ...     11   
2  I have been waiting over a week. Is the card s...     11   
3  Can I track my card while it is in the process...     11   
4  How do I know if I will get my card, or if it ...     11   

                            text_without_punctuation  \
0                      I am still waiting on my card   
1  What can I do if my card still hasnt arrived a...   
2  I have been waiting over a week Is the card st...   
3  Can I track my card while it is in the process...   
4  How do I know if I will get my card or if it i...   

                                          text_lower  \
0                      i am still waiting on my card   
1  what can i do if my card still hasnt arrived a...   
2  i have been waiting over a week is the card st...   
3  can i track my card while it is in the process...   
4  how do i know if i will get my card or if it i...   

             text_without_stopwords                   text_stemmed  \
0                still waiting card                still wait card   
1  card still hasnt arrived 2 weeks  card still hasnt arriv 2 week   
2    waiting week card still coming      wait week card still come   
3       track card process delivery    track card process deliveri   
4                know get card lost             know get card lost   

                  text_lemmatized  \
0                 still wait card   
1  card still hasnt arrive 2 week   
2       wait week card still come   
3     track card process delivery   
4              know get card lose   

                                  word2vec_embedding  \
0  [0.14740552, 0.49287963, -0.18150012, -0.17983...   
1  [0.13618965, 0.46497932, -0.19877052, -0.20180...   
2  [0.15524864, 0.5264305, -0.20263293, -0.218502...   
3  [0.12745024, 0.42099524, -0.14665046, -0.15708...   
4  [0.1624019, 0.5341237, -0.16616106, -0.2140869...   

                                     glove_embedding  \
0  [-0.009803335, 0.21815668, 0.41252002, -0.5842...   
1  [-0.11511, 0.24187951, 0.3228995, -0.26670733,...   
2  [-0.052110992, 0.2585094, 0.47082195, -0.54346...   
3  [0.10424499, -0.010438494, 0.14174, -0.1618157...   
4  [0.21422, 0.262195, 0.611615, -0.63392997, -0....   

                                  fasttext_embedding  
0  [-0.05346642, 0.049082335, -0.06296027, -0.227...  
1  [-0.025018776, 0.037596744, -0.052324012, -0.2...  
2  [-0.024247423, 0.04017203, -0.04614773, -0.261...  
3  [-0.11193083, 0.068958476, -0.063787036, -0.20...  
4  [-0.07586075, 0.036640003, -0.012725325, -0.21...

In [ ]:
!pip install sentence-transformers  # Install if you haven't already

from sentence_transformers import SentenceTransformer

# 1. Initialize the Sentence Transformer model
model_st = SentenceTransformer('all-mpnet-base-v2') # Choose a suitable model

# 2. Generate embeddings for your text data
df['sentence_embedding'] = df['text'].apply(lambda x: model_st.encode(x))

# Now, the 'sentence_embedding' column in your DataFrame 'df'
# will contain the generated embeddings for each text in the 'text' column.

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 109.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 86.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 55.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 88.8 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitli

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


0it [00:00, ?it/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
import h5py
import numpy as np

# Assuming your DataFrame is named 'df' and embeddings are in columns
# 'fasttext_embedding', 'glove_embedding', 'sentence_embedding'

# Convert embeddings to numpy arrays
fasttext_embeddings = np.vstack(df['fasttext_embedding'].values)
glove_embeddings = np.vstack(df['glove_embedding'].values)
sentence_transformer_embeddings = np.vstack(df['sentence_embedding'].values)

# Save embeddings to the .h5 file
with h5py.File('embeddings.h5', 'w') as hf:
    hf.create_dataset('fasttext_embeddings', data=fasttext_embeddings)
    hf.create_dataset('glove_embeddings', data=glove_embeddings)
    hf.create_dataset('sentence_transformer_embeddings', data=sentence_transformer_embeddings)

In [ ]:
import h5py
import pandas as pd
import os
from google.colab import drive

# Mount Google Drive (Optional: If you want to store on Drive)
drive.mount('/content/drive')

# Path to your embeddings file
embeddings_file = "embeddings.h5"  # Or "/content/drive/My Drive/embeddings.h5" for Google Drive

# Check if embeddings file exists
if os.path.exists(embeddings_file):
    # Load embeddings from file
    with h5py.File(embeddings_file, 'r') as hf:
        fasttext_embeddings = hf['fasttext_embeddings'][:]
        glove_embeddings = hf['glove_embeddings'][:]
        sentence_transformer_embeddings = hf['sentence_transformer_embeddings'][:]

    # Print shapes to verify loading
    print("FastText Embeddings Shape:", fasttext_embeddings.shape)
    print("GloVe Embeddings Shape:", glove_embeddings.shape)
    print("Sentence Transformer Embeddings Shape:", sentence_transformer_embeddings.shape)

    # Print a few embeddings to inspect values
    print("\nFastText Embeddings (First 5):\n", fasttext_embeddings[:5])
    print("\nGloVe Embeddings (First 5):\n", glove_embeddings[:5])
    print("\nSentence Transformer Embeddings (First 5):\n", sentence_transformer_embeddings[:5])

else:
    print(f"Embeddings file not found: {embeddings_file}")

Mounted at /content/drive
FastText Embeddings Shape: (10003, 100)
GloVe Embeddings Shape: (10003, 100)
Sentence Transformer Embeddings Shape: (10003, 768)

FastText Embeddings (First 5):
 [[-5.34664206e-02  4.90823351e-02 -6.29602671e-02 -2.27114603e-01
   4.51408736e-02 -4.48636226e-02  2.22143576e-01  1.49834439e-01
   3.48893911e-01  3.49268645e-01 -2.06771687e-01 -6.99522495e-02
   5.26335537e-02  5.51830828e-02 -2.54865408e-01  3.42231750e-01
   1.51367247e-01 -1.15777008e-01  3.00684827e-03  1.12416567e-02
   2.66360436e-02  1.27702013e-01  2.44518474e-01 -1.35729894e-01
  -5.94326556e-02 -1.06655575e-01 -7.83309788e-02  1.76323131e-01
  -7.62215704e-02  2.87299186e-01  3.84950601e-02  9.33878049e-02
  -2.18937397e-01  6.74221888e-02  3.74729373e-02 -4.99875331e-03
   1.98476180e-01 -5.76558821e-02  5.89184910e-02  3.90611701e-02
   2.26855323e-01  1.61934212e-01  1.72084495e-01 -6.78877681e-02
   9.05578211e-02 -1.43286005e-01 -4.77527976e-02  1.74443901e-01
   3.98713984e-02  1

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances, pairwise_distances
from scipy.spatial.distance import chebyshev, minkowski, jaccard

# Assuming you have a DataFrame 'df' with embeddings in columns like 'word2vec_embedding', 'glove_embedding', etc.

# Example: Calculating cosine similarity between two texts using Word2Vec embeddings
text1_embedding = df['word2vec_embedding'][0]  # Embedding of the first text
text2_embedding = df['word2vec_embedding'][1]  # Embedding of the second text

cosine_sim = cosine_similarity(text1_embedding.reshape(1, -1), text2_embedding.reshape(1, -1))

print(f"Cosine Similarity: {cosine_sim[0][0]}")

# Example: Calculating Euclidean distance between two texts using GloVe embeddings
text1_embedding = df['glove_embedding'][0]  # Embedding of the first text
text2_embedding = df['glove_embedding'][1]  # Embedding of the second text

euclidean_dist = euclidean_distances(text1_embedding.reshape(1, -1), text2_embedding.reshape(1, -1))

print(f"Euclidean Distance: {euclidean_dist[0][0]}")

# Calculating Manhattan distance
manhattan_dist = manhattan_distances(text1_embedding.reshape(1, -1), text2_embedding.reshape(1, -1))

print(f"Manhattan Distance: {manhattan_dist[0][0]}")

# Calculating Chebyshev distance
chebyshev_dist = chebyshev(text1_embedding, text2_embedding)

print(f"Chebyshev Distance: {chebyshev_dist}")

# Calculating Minkowski distance (with p=3 as an example)
minkowski_dist = minkowski(text1_embedding, text2_embedding, p=3)

print(f"Minkowski Distance (p=3): {minkowski_dist}")

# Calculating Jaccard distance
jaccard_dist = jaccard(text1_embedding, text2_embedding)

print(f"Jaccard Distance: {jaccard_dist}")


Cosine Similarity: 0.9991163611412048
Euclidean Distance: 1.9250236749649048
Manhattan Distance: 15.60965005500475
Chebyshev Distance: 0.5031316876411438
Minkowski Distance (p=3): 1.0272990465164185
Jaccard Distance: 1.0


 Install Qdrant Client



In [ ]:
!pip install qdrant-client

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.6/306.6 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 72.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 24.8 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.6
    Uninstalling protobuf-4.25.6:
      Successfully uninstalled protobuf-4.25.6


Import Libraries

In [ ]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
import pandas as pd

Create Qdrant Client and Collection

In [ ]:
# Create a Qdrant client
client = QdrantClient(":memory:")  # Or specify your Qdrant server address

# Define collection name and vector size
collection_name = "my_collection"
vector_size = 100  # Adjust based on your embedding size

# Create a collection
client.recreate_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)

<ipython-input-22-c8aa7c59aed8>:9: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  client.recreate_collection(


True

Prepare Data and Upsert Vectors

In [ ]:
# Assuming 'df' is your DataFrame with 'text' and 'label' columns
points = []
for index, row in df.iterrows():
    text = row['text']
    label = row['label']

    # Generate embedding for the text (replace with your embedding function)
    # embedding = your_embedding_function(text)
    embedding = row['glove_embedding']

    # Create payload
    payload = {"text": text, "intent": label}

    # Create PointStruct object
    point = PointStruct(id=index, vector=embedding.tolist(), payload=payload)
    points.append(point)

# Upsert points to Qdrant
client.upsert(collection_name=collection_name, points=points)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

 Perform Text Intent Search

In [ ]:
def search_qdrant(query_text, top_k=5):
    """Searches the Qdrant collection for similar texts.

    Args:
        query_text: The text to search for.
        top_k: The number of top results to return.

    Returns:
        A list of search results, each containing payload, score, label, and query.
    """
    import gensim.downloader as api
    glove_model = api.load("glove-wiki-gigaword-100")

    def create_glove_embedding(text):
        words = text.split()
        embeddings = [glove_model[word] for word in words if word in glove_model]
        if embeddings:
            return np.mean(embeddings, axis=0)
        else:
            return np.zeros(100)

    query_embedding = create_glove_embedding(query_text)
    query_embedding = query_embedding.reshape(1, -1).tolist()[0]

    search_result = client.search(
        collection_name=collection_name,
        query_vector=query_embedding,
        limit=top_k,
    )

    results = []
    for hit in search_result:
        results.append({
            "payload": hit.payload,
            "similarity": hit.score,
            "label": hit.payload.get("intent"),
            "query": query_text,
        })
    return results

# Get input from the user
user_query = input("Enter your query: ")

# Perform the search
search_results = search_qdrant(user_query)

# Display results in a readable format
print("\nSearch Results:")
for result in search_results:
    print(f"Query: {result['query']}")
    print(f"Label: {result['label']}")
    print(f"Similarity: {result['similarity']}")
    print(f"Payload: {result['payload']}")
    print("-" * 20)  # Separator between results

Enter your query: I forgot my code to get into the app.

Search Results:
Query: I forgot my code to get into the app.
Label: 22
Similarity: 0.9375111460235588
Payload: {'text': 'I think my card has been used by somebody else since I was never in the little town where some transactions on this bill have come from. Please stop this right away.', 'intent': 22}
--------------------
Query: I forgot my code to get into the app.
Label: 35
Similarity: 0.9334446121995417
Payload: {'text': "I tried to make a transfer like five different times. Why won't your system let me? Is it broke?", 'intent': 35}
--------------------
Query: I forgot my code to get into the app.
Label: 16
Similarity: 0.9329791591047355
Payload: {'text': "I think my card is being used by someone else to make purchases that I didn't authorize! I checked my account and see that there have been quite a few purchases over the last two days that I have no idea where they came from. We need to freeze my card now! And I need to find

<ipython-input-24-4b072bfb59e2>:25: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_result = client.search(


In [ ]:
def search_qdrant(query_text, top_k=5):
    """Searches the Qdrant collection for similar texts.

    Args:
        query_text: The text to search for.
        top_k: The number of top results to return.

    Returns:
        A list of search results, each containing payload, score, intent, and query.
    """
    import gensim.downloader as api
    import pandas as pd

    # Load the GloVe model
    glove_model = api.load("glove-wiki-gigaword-100")

    # Load the label-intent mapping file
    intent_mapping_file = "/content/intent.xlsx"  # Replace with the actual file path
    intent_data = pd.read_excel(intent_mapping_file)

    # Create a label-to-intent mapping dictionary
    label_to_intent = {
        row['label']: row['intent (category)'] for _, row in intent_data.iterrows()
    }

    def create_glove_embedding(text):
        words = text.split()
        embeddings = [glove_model[word] for word in words if word in glove_model]
        if embeddings:
            return np.mean(embeddings, axis=0)
        else:
            return np.zeros(100)

    query_embedding = create_glove_embedding(query_text)
    query_embedding = query_embedding.reshape(1, -1).tolist()[0]

    search_result = client.search(
        collection_name=collection_name,
        query_vector=query_embedding,
        limit=top_k,
    )

    results = []
    for hit in search_result:
        label = hit.payload.get("intent")
        intent = label_to_intent.get(label, "Unknown")
        results.append({
            "payload": hit.payload,
            "similarity": hit.score,
            "intent": intent,
            "query": query_text,
        })
    return results

# Get input from the user
user_query = input("Enter your query: ")

# Perform the search
search_results = search_qdrant(user_query)

# Display results in a readable format
print("\nSearch Results:")
for result in search_results:
    print(f"Query: {result['query']}")
    print(f"Intent: {result['intent']}")
    print(f"Similarity: {result['similarity']}")
    print(f"Payload: {result['payload']}")
    print("-" * 20)  # Separator between results


Enter your query: I forgot my code to get into the app.

Search Results:
Query: I forgot my code to get into the app.
Intent: compromised_card
Similarity: 0.9375111460235588
Payload: {'text': 'I think my card has been used by somebody else since I was never in the little town where some transactions on this bill have come from. Please stop this right away.', 'intent': 22}
--------------------
Query: I forgot my code to get into the app.
Intent: failed_transfer
Similarity: 0.9334446121995417
Payload: {'text': "I tried to make a transfer like five different times. Why won't your system let me? Is it broke?", 'intent': 35}
--------------------
Query: I forgot my code to get into the app.
Intent: card_payment_not_recognised
Similarity: 0.9329791591047355
Payload: {'text': "I think my card is being used by someone else to make purchases that I didn't authorize! I checked my account and see that there have been quite a few purchases over the last two days that I have no idea where they came 

<ipython-input-25-dad08dc2f084>:37: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_result = client.search(


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from qdrant_client import QdrantClient, models

# Assuming your data is in a Pandas DataFrame called 'df'
# with columns like 'text', 'label', and embeddings (e.g., 'glove_embedding')

# Choose your split ratio: 80/20 or 70/30
split_ratio = 0.7  # For 70/30 split, use 0.7; for 80/20, use 0.8

# Split the data into training and testing sets
train_df, test_df = train_test_split(
    df, test_size=1 - split_ratio, random_state=42
)  # Adjust random_state as needed

# Create Qdrant client and collection
client = QdrantClient(":memory:")
collection_name = "my_collection"
vector_size = 100  # Adjust based on your embedding size

client.recreate_collection(
    collection_name=collection_name,
    vectors_config=models.VectorParams(size=vector_size, distance=models.Distance.COSINE),
)

# Upsert training data into Qdrant
points = []
for index, row in train_df.iterrows():
    embedding = row['glove_embedding'].tolist()  # Assuming 'glove_embedding' column
    payload = {"text": row['text'], "intent": row['label']}
    point = models.PointStruct(id=index, vector=embedding, payload=payload)
    points.append(point)

client.upsert(collection_name=collection_name, points=points)

# Testing with search and adding notes
results = []
for index, row in test_df.iterrows():
    query_text = row['text']
    actual_intent = row['label']

    # Search in Qdrant
    search_result = client.search(
        collection_name=collection_name,
        query_vector=row['glove_embedding'].tolist(),
        limit=1,
    )

    predicted_intent = search_result[0].payload.get("intent") if search_result else None

    results.append(
        {
            "query": query_text,
            "actual": actual_intent,
            "search": predicted_intent,
            "intent": predicted_intent,  # 'intent' and 'search' are the same
            "predict": predicted_intent,  # 'predict' and 'search' are the same
        }
    )

results_df = pd.DataFrame(results)
print(results_df)

<ipython-input-26-f6830d900d5f>:21: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  client.recreate_collection(
<ipython-input-26-f6830d900d5f>:43: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_result = client.search(


                                                  query  actual  search  \
0        Is it possible for me to change my PIN number?      21      21   
1                  I'm not sure why my card didn't work      25      25   
2                        I don't think my top up worked      59      59   
3     Can you explain why my payment was charged a fee?      15      15   
4     How long does a transfer from a UK account tak...       5       5   
...                                                 ...     ...     ...   
2996  When I tried to top up using my card, all of t...      62      62   
2997                                I got charged twice      63      63   
2998                     can you express my card to me?      12      13   
2999                      I want to get a virtual card!      40      40   
3000            I did not get my virtual card yet, Why?      40      40   

      intent  predict  
0         21       21  
1         25       25  
2         59       59  
3  

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Assuming 'results_df' is the DataFrame containing your search results

# Extract actual and predicted intents
actual_intents = results_df['actual'].tolist()
predicted_intents = results_df['predict'].tolist()

# Calculate metrics
accuracy = accuracy_score(actual_intents, predicted_intents)
precision = precision_score(actual_intents, predicted_intents, average='weighted')  # or 'micro', 'macro'
recall = recall_score(actual_intents, predicted_intents, average='weighted')  # or 'micro', 'macro'
f1 = f1_score(actual_intents, predicted_intents, average='weighted')  # or 'micro', 'macro'

# Print the results
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.7907364211929356
Precision: 0.7992415829022378
Recall: 0.7907364211929356
F1 Score: 0.7918344818768164


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Assuming 'results_df' is the DataFrame containing your search results

# Extract actual and predicted intents
actual_intents = results_df['actual'].tolist()
predicted_intents = results_df['predict'].tolist()

# Generate confusion matrix
cm = confusion_matrix(actual_intents, predicted_intents)

# Print confusion matrix
print("Confusion Matrix:")
print(cm)

# Generate classification report
report = classification_report(actual_intents, predicted_intents)

# Print classification report
print("\nClassification Report:")
print(report)

Confusion Matrix:
[[28  0  0 ...  1  0  0]
 [ 0 40  0 ...  0  0  0]
 [ 1  0 31 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  1 32]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.67      0.72        42
           1       0.98      0.95      0.96        42
           2       0.97      0.91      0.94        34
           3       0.70      0.58      0.64        24
           4       0.89      0.85      0.87        39
           5       0.77      0.74      0.75        54
           6       0.94      0.82      0.87        55
           7       0.72      0.72      0.72        40
           8       0.84      0.87      0.85        53
           9       0.88      0.93      0.90        40
          10       0.89      0.67      0.76        24
          11       0.65      0.69      0.67        59
          12       0.81      0.59      0.69        37
          13       0.86      0.93      0.89  